# https://github.com/fluent/fluent-bit/tree/master/conf
# https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        Off
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          exec
    Command       python3 /fluent-bit/python-scripts/app_structured.py
    Interval_Sec  5
    Parser        json
    Tag           app_structured

[OUTPUT]
    Name          es
    Match         *
    Host          elasticsearch_master
    Port          9200
    Index         app_structured_logs
    Logstash_Format Off
    # Config de compatibilidad es 8.0.0
    Suppress_Type_Name On
    Retry_Limit   False
    Trace_Output  Off

[OUTPUT]
    Name          stdout
    Match         *
    Format        json