# https://github.com/fluent/fluent-bit/tree/master/conf
# https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          tail
    Path          /shared_logs/app_classic.log
    Parser        regex_logs
    Tag           app_classic

[OUTPUT]
    Name          es
    Match         app_classic
    Host          elasticsearch_master
    Port          9200
    Index         app_classic_logs
    # Config de compatibilidad es 8.0.0
    Suppress_Type_Name On
    Retry_Limit   False
    Trace_Output  Off

[OUTPUT]
    Name          stdout
    Match         *